// Command genregexpunicode regenerates pkg/vm/regex_unicode_data.go, the
// code point sets behind RegExp Unicode property escapes: every binary
// property, General_Category value, Script and Script_Extensions value
// ECMAScript defines, and the members of the properties of strings that can
// be enumerated. Go's unicode package carries only part of that data (no
// Script_Extensions, no emoji or case-change properties), so all of it is
// taken from one source for consistency.
//
// The sets are read out of a reference ECMAScript engine rather than parsed
// from the UCD files: node is asked, code point by code point, whether
// /\p{...}/u matches. Run it with a node whose Unicode version
// (process.versions.unicode) matches Go's unicode.Version, so these sets
// agree with the General_Category and Script tables the VM takes from Go:
//
//	go run ./tools/genregexpunicode > pkg/vm/regex_unicode_data.go
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"sort"
	"strings"
	"unicode"

	"github.com/nooga/paserati/pkg/jsregex"
)

const nodeScript = `
const bodies = JSON.parse(require('fs').readFileSync(0, 'utf8'));
const out = { unicode: process.versions.unicode, sets: [] };
for (const body of bodies) {
  const re = new RegExp('^' + body + '$', 'u');
  const ranges = [];
  let start = -1;
  for (let cp = 0; cp <= 0x10FFFF; cp++) {
    const m = re.test(String.fromCodePoint(cp));
    if (m && start < 0) start = cp;
    if (!m && start >= 0) { ranges.push(start, cp - 1); start = -1; }
  }
  if (start >= 0) ranges.push(start, 0x10FFFF);
  out.sets.push(ranges);
}

// Properties of strings, by testing every candidate their grammar in
// UTS #51 allows. RGI_Emoji_ZWJ_Sequence has no candidate space small
// enough to search and is left out.
const cps = (lo, hi) => Array.from({ length: hi - lo + 1 }, (_, i) => lo + i);
const all = cps(0, 0x10FFFF).filter(c => c < 0xD800 || c > 0xDFFF);
const emoji = all.filter(c => /\p{Emoji}/u.test(String.fromCodePoint(c)));
const ri = cps(0x1F1E6, 0x1F1FF);
const tagAlnum = [...cps(0xE0030, 0xE0039), ...cps(0xE0061, 0xE007A)];
const tagAlpha = cps(0xE0061, 0xE007A);
const candidates = {
  Basic_Emoji: function* () { for (const c of all) { yield [c]; yield [c, 0xFE0F]; } },
  Emoji_Keycap_Sequence: function* () { for (const c of cps(0, 0x7F)) yield [c, 0xFE0F, 0x20E3]; },
  RGI_Emoji_Flag_Sequence: function* () { for (const a of ri) for (const b of ri) yield [a, b]; },
  RGI_Emoji_Modifier_Sequence: function* () {
    for (const c of emoji) for (const m of cps(0x1F3FB, 0x1F3FF)) yield [c, m];
  },
  RGI_Emoji_Tag_Sequence: function* () {
    for (const a of tagAlpha) for (const b of tagAlpha) {
      for (const c of tagAlnum) {
        yield [0x1F3F4, a, b, c, 0xE007F];
        for (const d of tagAlnum) {
          yield [0x1F3F4, a, b, c, d, 0xE007F];
          for (const e of tagAlnum) yield [0x1F3F4, a, b, c, d, e, 0xE007F];
        }
      }
    }
  },
};
out.strings = {};
for (const [name, gen] of Object.entries(candidates)) {
  const re = new RegExp('^\\p{' + name + '}$', 'v');
  const found = [];
  for (const s of gen()) if (re.test(String.fromCodePoint(...s))) found.push(s);
  out.strings[name] = found;
}
process.stdout.write(JSON.stringify(out));
`

type query struct{ key, body string }

func main() {
	var queries []query
	for _, name := range jsregex.BinaryPropertyNames() {
		queries = append(queries, query{name, `\p{` + name + `}`})
	}
	for _, name := range jsregex.GeneralCategoryNames() {
		queries = append(queries, query{"gc=" + name, `\p{General_Category=` + name + `}`})
	}
	for _, name := range jsregex.ScriptNames() {
		queries = append(queries, query{"sc=" + name, `\p{Script=` + name + `}`})
	}
	for _, name := range jsregex.ScriptNames() {
		queries = append(queries, query{"scx=" + name, `\p{Script_Extensions=` + name + `}`})
	}

	bodies := make([]string, len(queries))
	for i, q := range queries {
		bodies[i] = q.body
	}
	in, _ := json.Marshal(bodies)
	cmd := exec.Command("node", "-e", nodeScript)
	cmd.Stdin = bytes.NewReader(in)
	cmd.Stderr = os.Stderr
	raw, err := cmd.Output()
	if err != nil {
		log.Fatalf("node: %v", err)
	}
	var result struct {
		Unicode string
		Sets    [][]int
		Strings map[string][][]rune
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		log.Fatal(err)
	}
	if !strings.HasPrefix(unicode.Version, result.Unicode) {
		log.Fatalf("node has Unicode %s but Go has %s", result.Unicode, unicode.Version)
	}

	var b strings.Builder
	b.WriteString("// Code generated by go run ./tools/genregexpunicode; DO NOT EDIT.\n\n")
	b.WriteString("package vm\n\n")
	fmt.Fprintf(&b, "// generatedUnicodeVersion is the Unicode version these sets were read at.\n")
	fmt.Fprintf(&b, "const generatedUnicodeVersion = %q\n\n", result.Unicode)
	b.WriteString("// generatedUnicodeSets maps a binary property name, or \"gc=\", \"sc=\" or\n")
	b.WriteString("// \"scx=\" and a value, to its code point ranges: base64 of uvarint pairs,\n")
	b.WriteString("// each range as (lo - previous hi - 1, hi - lo).\n")
	b.WriteString("var generatedUnicodeSets = map[string]string{\n")
	for i, q := range queries {
		fmt.Fprintf(&b, "\t%q: %q,\n", q.key, encodeRanges(result.Sets[i]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// generatedStringProperties lists the members of each property of strings\n")
	b.WriteString("// whose members can be enumerated (all but RGI_Emoji_ZWJ_Sequence and the\n")
	b.WriteString("// RGI_Emoji union).\n")
	b.WriteString("var generatedStringProperties = map[string][]string{\n")
	names := make([]string, 0, len(result.Strings))
	for name := range result.Strings {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: {", name)
		for i, s := range result.Strings[name] {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%+q", string(s))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	os.Stdout.Write(src)
}

func encodeRanges(r []int) string {
	var buf []byte
	next := 0
	for i := 0; i < len(r); i += 2 {
		buf = binary.AppendUvarint(buf, uint64(r[i]-next))
		buf = binary.AppendUvarint(buf, uint64(r[i+1]-r[i]))
		next = r[i+1] + 1
	}
	return base64.StdEncoding.EncodeToString(buf)
}
